project:
  type: website
  output-dir: docs

website:
  title: "R-4.4.1-Issue_Board"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    comments: 
      utterances:
        repo: quarto-dev/quarto-web    

editor: visual

